/**
 * =============================================================================
 * CLIQUE CREATE PAGE - Form a new Clique
 * =============================================================================
 * 
 * A full-page form for creating a new clique with:
 * - Clique name
 * - Theme tags (up to 5)
 * - Commitment style
 * - Organization code (optional)
 * 
 * Creator becomes Clique Leader by default.
 * Max 6 members per clique.
 */

import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { 
  Users, 
  ArrowLeft, 
  Sparkles, 
  CalendarClock, 
  Compass,
  Check,
  Loader2,
  Link as LinkIcon,
  Copy
} from 'lucide-react';

// Available theme tags with emojis
const THEME_TAGS = [
  { value: 'movies', label: 'Movies', emoji: '🎬' },
  { value: 'outdoors', label: 'Outdoors', emoji: '🥾' },
  { value: 'food', label: 'Food & Drink', emoji: '🍕' },
  { value: 'music', label: 'Music', emoji: '🎵' },
  { value: 'fitness', label: 'Fitness', emoji: '💪' },
  { value: 'gaming', label: 'Gaming', emoji: '🎮' },
  { value: 'arts', label: 'Arts & Culture', emoji: '🎨' },
  { value: 'sports', label: 'Sports', emoji: '⚽' },
  { value: 'books', label: 'Books', emoji: '📚' },
  { value: 'travel', label: 'Travel', emoji: '✈️' },
  { value: 'coffee', label: 'Coffee & Tea', emoji: '☕' },
  { value: 'wellness', label: 'Wellness', emoji: '🧘' },
  { value: 'tech', label: 'Tech', emoji: '💻' },
  { value: 'nature', label: 'Nature', emoji: '🌿' },
  { value: 'pets', label: 'Pets', emoji: '🐕' },
  { value: 'nightlife', label: 'Nightlife', emoji: '🌙' },
];

// Commitment styles
const COMMITMENT_STYLES = [
  {
    value: 'casual',
    label: 'Casual',
    description: 'Meet when it works for everyone',
    icon: Sparkles,
  },
  {
    value: 'ritual',
    label: 'Ritual',
    description: 'Regular schedule (weekly, monthly)',
    icon: CalendarClock,
  },
  {
    value: 'quest-based',
    label: 'Quest-Based',
    description: 'Specific adventures and goals',
    icon: Compass,
  },
];

export default function CliqueCreate() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [createdClique, setCreatedClique] = useState<{
    id: string;
    name: string;
    invite_code: string;
  } | null>(null);

  // Form state
  const [name, setName] = useState('');
  const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const [commitmentStyle, setCommitmentStyle] = useState('casual');
  const [orgCode, setOrgCode] = useState('');

  const toggleTag = (tag: string) => {
    if (selectedTags.includes(tag)) {
      setSelectedTags(selectedTags.filter(t => t !== tag));
    } else if (selectedTags.length < 5) {
      setSelectedTags([...selectedTags, tag]);
    } else {
      toast.error('Maximum 5 tags allowed');
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!user) {
      toast.error('Please sign in to create a clique');
      navigate('/auth');
      return;
    }

    if (!name.trim()) {
      toast.error('Please enter a clique name');
      return;
    }

    setIsSubmitting(true);

    try {
      // Create the clique (invite_code is auto-generated by trigger)
      const { data: clique, error: cliqueError } = await supabase
        .from('squads')
        .insert({
          name: name.trim(),
          theme_tags: selectedTags,
          commitment_style: commitmentStyle,
          org_code: orgCode.trim() || null,
          visibility: 'private',
          max_members: 6,
        })
        .select('id, name, invite_code')
        .single();

      if (cliqueError) throw cliqueError;

      // Add creator as Clique Leader (persistent_squad_id only - squad_id is for quest_squads)
      const { error: memberError } = await supabase
        .from('squad_members')
        .insert({
          persistent_squad_id: clique.id,
          user_id: user.id,
          role: 'leader',
          status: 'active',
        });

      if (memberError) throw memberError;

      setCreatedClique(clique);
      toast.success('Clique created! 🎉');
    } catch (error: any) {
      console.error('Error creating clique:', error);
      toast.error(error.message || 'Failed to create clique');
    } finally {
      setIsSubmitting(false);
    }
  };

  const copyInviteLink = () => {
    if (createdClique?.invite_code) {
      const link = `${window.location.origin}/join/${createdClique.invite_code}`;
      navigator.clipboard.writeText(link);
      toast.success('Invite link copied!');
    }
  };

  const copyInviteCode = () => {
    if (createdClique?.invite_code) {
      navigator.clipboard.writeText(createdClique.invite_code);
      toast.success('Invite code copied!');
    }
  };

  // Success state
  if (createdClique) {
    const inviteLink = `${window.location.origin}/join/${createdClique.invite_code}`;
    
    return (
      <div className="min-h-dvh bg-background flex flex-col">
        <Navbar />
        
        <main className="flex-1 container mx-auto px-4 py-8">
          <div className="max-w-xl mx-auto">
            <Card className="border-primary/20">
              <CardHeader className="text-center pb-4">
                <div className="w-16 h-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4">
                  <Check className="h-8 w-8 text-primary" />
                </div>
                <CardTitle className="text-2xl font-display">
                  {createdClique.name} is Ready!
                </CardTitle>
                <CardDescription>
                  You're the Clique Leader. Invite up to 5 more members.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* Invite Code */}
                <div className="space-y-2">
                  <Label>Invite Code</Label>
                  <div className="flex gap-2">
                    <Input 
                      value={createdClique.invite_code} 
                      readOnly 
                      className="font-mono text-lg tracking-wider"
                    />
                    <Button variant="outline" size="icon" onClick={copyInviteCode}>
                      <Copy className="h-4 w-4" />
                    </Button>
                  </div>
                </div>

                {/* Invite Link */}
                <div className="space-y-2">
                  <Label>Shareable Link</Label>
                  <div className="flex gap-2">
                    <Input 
                      value={inviteLink} 
                      readOnly 
                      className="text-sm"
                    />
                    <Button variant="outline" size="icon" onClick={copyInviteLink}>
                      <LinkIcon className="h-4 w-4" />
                    </Button>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex flex-col gap-3 pt-4">
                  <Button 
                    className="w-full" 
                    onClick={() => navigate(`/cliques/${createdClique.id}`)}
                  >
                    <Users className="h-4 w-4 mr-2" />
                    Go to Your Clique
                  </Button>
                  <Button 
                    variant="outline" 
                    className="w-full"
                    onClick={() => navigate('/profile?tab=cliques')}
                  >
                    View All Cliques
                  </Button>
                </div>
              </CardContent>
            </Card>
          </div>
        </main>

        <Footer />
      </div>
    );
  }

  return (
    <div className="min-h-dvh bg-background flex flex-col">
      <Navbar />
      
      <main className="flex-1 container mx-auto px-4 py-8">
        <div className="max-w-2xl mx-auto">
          {/* Back Button */}
          <Button 
            variant="ghost" 
            className="mb-6"
            onClick={() => navigate('/profile?tab=cliques')}
          >
            <ArrowLeft className="h-4 w-4 mr-2" />
            Back to My Cliques
          </Button>

          <Card>
            <CardHeader>
              <div className="flex items-center gap-3 mb-2">
                <div className="p-2.5 rounded-full bg-primary/10">
                  <Users className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <CardTitle className="text-2xl font-display">Form a Clique</CardTitle>
                  <CardDescription>
                    Create your own crew for real-world adventures
                  </CardDescription>
                </div>
              </div>
            </CardHeader>

            <CardContent>
              <form onSubmit={handleSubmit} className="space-y-8">
                {/* Clique Name */}
                <div className="space-y-2">
                  <Label htmlFor="name">Clique Name *</Label>
                  <Input
                    id="name"
                    placeholder="e.g., The Bagel Boys, Trail Blazers..."
                    value={name}
                    onChange={(e) => setName(e.target.value)}
                    maxLength={50}
                    className="text-lg"
                  />
                  <p className="text-xs text-muted-foreground">
                    {name.length}/50 characters
                  </p>
                </div>

                {/* Theme Tags */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <Label>Theme Tags</Label>
                    <span className="text-xs text-muted-foreground">
                      {selectedTags.length}/5 selected
                    </span>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {THEME_TAGS.map((tag) => {
                      const isSelected = selectedTags.includes(tag.value);
                      return (
                        <Badge
                          key={tag.value}
                          variant={isSelected ? 'default' : 'outline'}
                          className={`cursor-pointer transition-all text-sm py-1.5 px-3 ${
                            isSelected 
                              ? 'bg-primary hover:bg-primary/90' 
                              : 'hover:bg-muted'
                          }`}
                          onClick={() => toggleTag(tag.value)}
                        >
                          <span className="mr-1.5">{tag.emoji}</span>
                          {tag.label}
                        </Badge>
                      );
                    })}
                  </div>
                  <p className="text-xs text-muted-foreground">
                    Pick up to 5 themes that describe your clique
                  </p>
                </div>

                {/* Commitment Style */}
                <div className="space-y-3">
                  <Label>Commitment Style</Label>
                  <RadioGroup 
                    value={commitmentStyle} 
                    onValueChange={setCommitmentStyle}
                    className="grid gap-3"
                  >
                    {COMMITMENT_STYLES.map((style) => {
                      const Icon = style.icon;
                      return (
                        <Label
                          key={style.value}
                          htmlFor={style.value}
                          className={`flex items-center gap-4 p-4 rounded-lg border cursor-pointer transition-all ${
                            commitmentStyle === style.value
                              ? 'border-primary bg-primary/5'
                              : 'border-border hover:border-muted-foreground/50'
                          }`}
                        >
                          <RadioGroupItem 
                            value={style.value} 
                            id={style.value}
                            className="sr-only"
                          />
                          <div className={`p-2 rounded-lg ${
                            commitmentStyle === style.value
                              ? 'bg-primary/10'
                              : 'bg-muted'
                          }`}>
                            <Icon className={`h-5 w-5 ${
                              commitmentStyle === style.value
                                ? 'text-primary'
                                : 'text-muted-foreground'
                            }`} />
                          </div>
                          <div className="flex-1">
                            <p className="font-medium">{style.label}</p>
                            <p className="text-sm text-muted-foreground">
                              {style.description}
                            </p>
                          </div>
                          {commitmentStyle === style.value && (
                            <Check className="h-5 w-5 text-primary" />
                          )}
                        </Label>
                      );
                    })}
                  </RadioGroup>
                </div>

                {/* Organization Code */}
                <div className="space-y-2">
                  <Label htmlFor="orgCode">Organization Code (optional)</Label>
                  <Input
                    id="orgCode"
                    placeholder="e.g., UT-AUSTIN, ACME-CORP..."
                    value={orgCode}
                    onChange={(e) => setOrgCode(e.target.value.toUpperCase())}
                    maxLength={30}
                    className="uppercase"
                  />
                  <p className="text-xs text-muted-foreground">
                    Connect your clique to a school, company, or community
                  </p>
                </div>

                {/* Info Box */}
                <div className="bg-muted/50 rounded-lg p-4 space-y-2">
                  <div className="flex items-center gap-2 text-sm font-medium">
                    <Users className="h-4 w-4 text-primary" />
                    <span>Max 6 members per clique</span>
                  </div>
                  <p className="text-sm text-muted-foreground">
                    You'll be the Clique Leader with admin permissions. 
                    Invite friends with your unique code after creation.
                  </p>
                </div>

                {/* Submit */}
                <Button 
                  type="submit" 
                  className="w-full" 
                  size="lg"
                  disabled={isSubmitting || !name.trim()}
                >
                  {isSubmitting ? (
                    <>
                      <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                      Creating...
                    </>
                  ) : (
                    <>
                      <Users className="h-4 w-4 mr-2" />
                      Create Clique
                    </>
                  )}
                </Button>
              </form>
            </CardContent>
          </Card>
        </div>
      </main>

      <Footer />
    </div>
  );
}
